name: Build and Deploy

on: [push]

jobs:
  build:
    name: Build Gatsby Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Gatsby Site
        env:
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          GATSBY_CLOUDINARY_CLOUD_NAME: ${{ secrets.GATSBY_CLOUDINARY_CLOUD_NAME }}
          GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        uses: jzweifel/gatsby-cli-github-action@master
        with:
          gatsby-arg: build
      - name: Deploy to Greenman 
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-username: ${{ secrets.SFTP_USERNAME }}
          ftp-server: sftp://${{ secrets.SFTP_SERVER }}:22/web
          ftp-password: ${{ secrets.SFTP_PASSWORD }}
          local-dir: public
          git-ftp-args: --insecure
